server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qinhaohao1114/spring-cloud-config-demo.git
          username: qinhaohao1114
          password: qhh18260639556
          search-paths:
            - spring-cloud-config-demo
      label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin