spring:
  application:
    name: netflix-eureka-server

---
spring:
  profiles: netflixServerA
server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka

---
spring:
  profiles: netflixServerB
server:
  port: 8762
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka